### PR TITLE
Edited research pages

### PR DESCRIPTION
**Pull request by rebeccagmartin**

### CODE REVIEW

**Comment by zhuzh1983** [comment]
@chaochinyang, @rebeccagmartin  I am not sure that we want to add more sections (I see that there are two new sections with planets in binary and circumplanetary disks) to the research page. The research page is for some general descriptions on the research topics that we are working on (disk, planet formation, planet). It is more for general public and potential future students. We may not want to go into details. I suggest that we just give a general description on the topics. Please feel free to add subsections under each category, or we can merge some subsections into bigger more general sections (e.g. streaming instability can be merged with dust-gas dynamics,  and MHD, vertical shear, GI can be merged into turbulence. I am not sure that we actually want to go into that detail).  I also suggest that we move all references to news section (we are free to write news on each paper there). We can leave the reference of figures in the research page though. Since we won't change/update the research page very often, we want to leave it as general as possible. If we are doing something differently tomorrow, then we don't need to change or extend the research section.

**Review by zhuzh1983 — COMMENTED** [review]
@chaochinyang, @rebeccagmartin I am not sure that we want to add more sections (I see that there are two new sections with planets in binary and circumplanetary disks) to the research page. I think the research page is for some general descriptions on the research topics that we are working on (disk, planet formation, planet). It is more for general public and attracting potential future students. I suggest that we just give a general description on the topics. Please feel free to add subsections under each category, or we can merge some subsections into bigger more general sections (e.g. streaming instability can be merged with dust-gas dynamics, and MHD, vertical shear, GI can be merged into turbulence. I am not sure that we actually want to go into that detail). I also suggest that we move all references to news section (we are free to write news on each paper there). We can leave the reference of figures in the research page though. Since we won't change/update the research page very often, we want to leave it as general as possible (If we are doing something differently tomorrow, then we don't need to change or extend the research section.). If you prefer a more detailed research page, we can discuss how to arrange them. But I worry that we may need to update them very often in that case, and not many people will actually read through them. Those detailed individual research projects are more suited in the news section.

**Comment by rebeccagmartin** [comment]
OK please delete what I did.

**Comment by sabaronett** [comment]
@zhuzh1983, am I OK to close this PR?

**Comment by zhuzh1983** [comment]
Please close this.

Thanks,
-----------------------------
Zhaohuan Zhu
Associate Professor, Physics & Astronomy
University of Nevada - Las Vegas
Email: ***@***.***
Homepage: www.physics.unlv.edu/~zhzhu

**Pull request closed without merging**
